---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: books-api
    version: v1
    app.kubernetes.io/part-of: library-books-api
    app.kubernetes.io/name: books-api-v1
  name: books-api-v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: books-api
    version: v1
    app.kubernetes.io/part-of: library-books-api
    app.kubernetes.io/name: books-api-v1
  name: books-api-v1-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: books-api-v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: books-api
    version: v1
    app.kubernetes.io/part-of: library-books-api
    app.kubernetes.io/name: books-api-v1
  name: books-api-v1-config
data:
  quarkus.jaeger.endpoint: http://jaeger-all-in-one-inmemory-collector.demo-observability.svc:14268/api/traces
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api-v1
  labels:
    app: books-api
    version: v1
    app.kubernetes.io/part-of: library-books-api
    app.kubernetes.io/name: books-api-v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
      version: v1
      app.kubernetes.io/part-of: library-books-api
      app.kubernetes.io/name: books-api-v1      
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app: books-api
        version: v1
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/part-of: library-books-api
        app.kubernetes.io/name: books-api-v1
    spec:
      containers:
        - name: books-api-v1
          image: quay.io/jnyilimbibi/demo-books-api:v1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 256Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: books-api-v1
---
apiVersion: v1
kind: Service
metadata:
  name: books-api-v1
  labels:
    app: books-api
    version: v1
    app.kubernetes.io/part-of: library-books-api
    app.kubernetes.io/name: books-api-v1
    discovery.3scale.net: "true"
  annotations:
    discovery.3scale.net/port: "80"
    discovery.3scale.net/scheme: "http"
    discovery.3scale.net/path: "/api/v1"
    discovery.3scale.net/description-path: "/openapi.json"
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: books-api
    version: v1
    app.kubernetes.io/name: books-api-v1
    app.kubernetes.io/part-of: library-books-api
  type: ClusterIP