apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threescale-dev
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/library-books-api/overlays/dev
    repoURL: https://github.com/sgutierr/3scalegitops.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
