apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: library-books-api
spec:
  productCRName: library-books-api
  production: true