apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: books-api-v1-backend
spec:
  name: books-api-v1 Backend
  systemName: books-api-v1-backend
  privateBaseURL: https://echo-api.3scale.net
  description: 'Manages a library books inventory (v1)'
  providerAccountRef:
    name: tenant-secret